#!/usr/bin/env python3
"""Bake Wavefront OBJ models into vendor/models.js.

The game is fully self-contained (Three.js itself is vendored so it runs
offline and from file://). To keep that property for the uploaded Blender
models, we don't fetch .obj files at runtime — instead we quantise their
geometry and emit a small ES module that decodes synchronously in the browser.

Positions only (normals are recomputed in-game): each object is centred on the
origin and scaled so its longest axis spans 1.0, then stored as int16. Faces are
fan-triangulated and split per `usemtl` group so materials (e.g. eyes) can be
coloured independently.

Usage:  python3 tools/bake_models.py
Source OBJs live in assets/models/.
"""
import base64
import json
import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "models")
# Map output model key -> (obj filename, optional object-name filter)
SOURCES = [
    ("shark.obj", None),
    ("free_fish_pack.obj", None),
]


def parse(path):
    objs = []          # list of (name, {material: [vertex indices...]})
    verts = []
    cur = parts = curmat = None

    def newobj(name):
        nonlocal cur, parts, curmat
        cur, parts, curmat = name, {}, None
        objs.append((name, parts))

    with open(path) as fh:
        for line in fh:
            if line.startswith("v "):
                verts.append([float(x) for x in line.split()[1:4]])
            elif line.startswith("o "):
                newobj(line[2:].strip())
            elif line.startswith("usemtl"):
                bits = line.split()
                curmat = bits[1] if len(bits) > 1 else "default"
                if parts is None:
                    newobj("obj")
                parts.setdefault(curmat, [])
            elif line.startswith("f "):
                if parts is None:
                    newobj("obj")
                if curmat is None:
                    curmat = "default"
                    parts.setdefault(curmat, [])
                idx = []
                for tk in line.split()[1:]:
                    vi = int(tk.split("/")[0])
                    idx.append(vi - 1 if vi > 0 else len(verts) + vi)
                for k in range(1, len(idx) - 1):       # fan triangulation
                    parts[curmat].extend([idx[0], idx[k], idx[k + 1]])
    return verts, objs


def bake_object(verts, parts):
    used = set()
    for tri in parts.values():
        used.update(tri)
    xs = [verts[i][0] for i in used]
    ys = [verts[i][1] for i in used]
    zs = [verts[i][2] for i in used]
    cx, cy, cz = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2, (min(zs) + max(zs)) / 2
    dx, dy, dz = max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs)
    longest = max(dx, dy, dz) or 1.0
    out_parts = []
    for mat, tri in parts.items():
        if not tri:
            continue
        buf = bytearray()
        for vi in tri:
            p = verts[vi]
            for c, off in ((p[0], cx), (p[1], cy), (p[2], cz)):
                q = max(-32768, min(32767, int(round(((c - off) / longest) * 32767))))
                buf += struct.pack("<h", q)
        out_parts.append({"m": mat, "p": base64.b64encode(bytes(buf)).decode()})
    dims = [round(dx / longest, 4), round(dy / longest, 4), round(dz / longest, 4)]
    return {"dims": dims, "parts": out_parts}


def main():
    data = {}
    for fname, _ in SOURCES:
        verts, objs = parse(os.path.join(SRC, fname))
        if fname.startswith("shark"):
            data["shark"] = bake_object(verts, objs[0][1])
        else:
            for name, parts in objs:
                data[name] = bake_object(verts, parts)

    js = (
        "// Auto-generated by tools/bake_models.py from the uploaded Blender OBJ models.\n"
        "// Positions only, int16-quantized and normalized so the model's longest\n"
        "// axis spans 1.0 (centred on origin). Decoded synchronously — no network,\n"
        "// works offline and from file://, matching the vendored-Three.js approach.\n"
        "const DATA = " + json.dumps(data, separators=(",", ":")) + ";\n\n"
        "function b64ToI16(b64) {\n"
        "  const bin = atob(b64), len = bin.length, bytes = new Uint8Array(len);\n"
        "  for (let i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);\n"
        "  return new Int16Array(bytes.buffer);\n"
        "}\n"
        "export function modelNames() { return Object.keys(DATA); }\n"
        "export function getModel(name) {\n"
        "  const d = DATA[name];\n"
        "  if (!d) return null;\n"
        "  return {\n"
        "    dims: d.dims,\n"
        "    parts: d.parts.map((p) => {\n"
        "      const i16 = b64ToI16(p.p);\n"
        "      const pos = new Float32Array(i16.length);\n"
        "      for (let i = 0; i < i16.length; i++) pos[i] = i16[i] / 32767;\n"
        "      return { material: p.m, positions: pos };\n"
        "    }),\n"
        "  };\n"
        "}\n"
    )
    out = os.path.join(ROOT, "vendor", "models.js")
    with open(out, "w") as fh:
        fh.write(js)
    print("wrote", out, round(len(js) / 1024, 1), "KB")
    for k, v in data.items():
        print(" ", k, "dims", v["dims"], "parts", [p["m"] for p in v["parts"]])


if __name__ == "__main__":
    main()
